### ISSUE TITLE
关于标签

### ISSUE THREAD

**Issue by ttianwang** [RSIA-LIESMARS-WHU/RSOD-Dataset-#1]
你好，我想问一下这个数据集的所标的标签是待检测物体左下角和右上角的坐标吗，谢谢

**Comment by beibeiZ** [comment]
你好，这个数据集你使用可以吗？我怎么在faster rcnn和retinaNet跑都报错

**Comment by ttianwang** [comment]
可以用的 @beibeiZ

**Comment by beibeiZ** [comment]
那你什么网络下跑的呢？我怎么都报bbox错误？



---原始邮件---
发件人: "wtt"<notifications@github.com&gt;
发送时间: 2019年9月12日(星期四) 晚上8:17
收件人: "RSIA-LIESMARS-WHU/RSOD-Dataset-"<RSOD-Dataset-@noreply.github.com&gt;;
抄送: "beibeiZ"<1532823435@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [RSIA-LIESMARS-WHU/RSOD-Dataset-] 关于标签 (#1)



可以用的 @beibeiZ

**Comment by ttianwang** [comment]
你可以说一下你的错误信息吗 @beibeiZ

**Comment by beibeiZ** [comment]
faster rcnn下报错，停止不运行：

retinaNet








------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月12日(星期四) 晚上8:23
收件人: "RSIA-LIESMARS-WHU/RSOD-Dataset-"<RSOD-Dataset-@noreply.github.com>; 
抄送: "张贝贝_2018206190048"<1532823435@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [RSIA-LIESMARS-WHU/RSOD-Dataset-] 关于标签 (#1)




你可以说一下你的错误信息吗 @beibeiZ

**Comment by ttianwang** [comment]
这个数据是没问题的，你看看是不是你转换的时候出的错

**Comment by beibeiZ** [comment]
没有转换，解压后直接用了？您之前用什么网络跑过吗？之前跑数据集没有出现这个问题




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月12日(星期四) 晚上8:36
收件人: "RSIA-LIESMARS-WHU/RSOD-Dataset-"<RSOD-Dataset-@noreply.github.com>; 
抄送: "张贝贝_2018206190048"<1532823435@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [RSIA-LIESMARS-WHU/RSOD-Dataset-] 关于标签 (#1)




这个数据是没问题的，你看看是不是你转换的时候出的错

**Comment by ttianwang** [comment]
我用的FPN网络，然后用的时候是把数据转成了tfrecord类型的

**Comment by beibeiZ** [comment]
我都是直接以voc数据类型用的，不知道为什么




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月12日(星期四) 晚上8:42
收件人: "RSIA-LIESMARS-WHU/RSOD-Dataset-"<RSOD-Dataset-@noreply.github.com>; 
抄送: "张贝贝_2018206190048"<1532823435@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [RSIA-LIESMARS-WHU/RSOD-Dataset-] 关于标签 (#1)




我用的FPN网络，然后用的时候是把数据转成了tfrecord类型的

**Comment by ttianwang** [comment]
那应该是你转换标签的时候出错了

**Comment by beibeiZ** [comment]
没转化，本身不都是voc数据类型呀




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月12日(星期四) 晚上8:59
收件人: "RSIA-LIESMARS-WHU/RSOD-Dataset-"<RSOD-Dataset-@noreply.github.com>; 
抄送: "张贝贝_2018206190048"<1532823435@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [RSIA-LIESMARS-WHU/RSOD-Dataset-] 关于标签 (#1)




那应该是你转换标签的时候出错了

**Comment by ttianwang** [comment]
这个我就不知道了我这边是没问题的

**Comment by beibeiZ** [comment]
好的，谢谢了




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月12日(星期四) 晚上9:01
收件人: "RSIA-LIESMARS-WHU/RSOD-Dataset-"<RSOD-Dataset-@noreply.github.com>; 
抄送: "张贝贝_2018206190048"<1532823435@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [RSIA-LIESMARS-WHU/RSOD-Dataset-] 关于标签 (#1)




这个我就不知道了我这边是没问题的
